# GitHub Pages Configuration
# This repository serves static HTML files directly

# Default page: index.html
# Main app: app.html

# Users:
# - admin / admin123
# - usuario1 / pass123  
# - demo / demo123
